version: "3.7"
services:
  auth:
    platform: linux/x86_64
    container_name: local-auth
    build: 
      context: ./auth
      dockerfile: Dockerfile
    volumes: 
    - .:/backend
    ports:
    - 3000:3000
  mongo:
    container_name: local-mongo
    image: mongo
    ports:
    - 27017:27017
    volumes: 
    - /data/db
